version: '3.4'

services:
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: ecommapi_backend
    restart: always
    env_file: config/.env
    command:
      [
        "sh",
        "-c",
        "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 -m manage.py runserver 0.0.0.0:8000 --nothreading --noreload"
      ]
    voulems:
      - .:/app
    ports:
      - 8000:8000
      - 5678:5678
    depends_on:
      - db

  db:
    image: postgres:14.2
    container_name: ecommapi_postgres
    restart: always
    env_file: config/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
