version: '3.4'

services:
  db:
    image: postgres:14.2
    container_name: ecommapi_postgres
    restart: always
    env_file: ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: gunicorn src.wsgi:application --bind=0.0.0.0:8000 --workers=4 --chdir="/app"
    container_name: ecommapi_backend
    restart: always
    env_file: ./.env
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db

  stripe-cli:
    image: stripe/stripe-cli:latest
    container_name: stripe-cli
    network_mode: host
    env_file: ./.env
    command: listen --api-key ${STRIPE_SECRET_KEY} --forward-to 127.0.0.1:8000/api/stripe/webhook/ --skip-verify

volumes:
  postgres_data:
