# Generated by Django 4.0 on 2022-04-09 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.ManyToManyField(related_name='userprofile', to='accounts.UserAddress'),
        ),
    ]
