# Generated by Django 4.0 on 2022-04-08 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_cart_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='min_order_total',
            field=models.IntegerField(default=0),
        ),
    ]
