# Generated by Django 4.0 on 2022-04-04 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productreview',
            old_name='created_at',
            new_name='created',
        ),
        migrations.AddField(
            model_name='productreview',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
